### ISSUE TITLE
Asking for advice

### ISSUE THREAD

**Issue by djape1** [unspok3n/beatportdl#11]
Hello unspok3n,
I found the project interesting and tried to use it - bpdl last version on win10.
But where do I wrong, I always getting result below.
I read issues at closed section and saw it works for anybody.

Logging in
Authorizing
Issuing token
Enter track or release link: https://www.beatport.com/release/releases/121284
save track: request failed with status code: 403 - You do not have permission to perform this action.
save track: request failed with status code: 403 - You do not have permission to perform this action.
Enter track or release link:

**Comment by unspok3n** [comment]
Hi, are you sure that you have the right beatport streaming subscription?

**Comment by Darkdani31** [comment]
hi
![image](https://github.com/user-attachments/assets/aaba33fc-6bd3-4558-b89a-379c18b53ef9)

with advanced subcription...
by the past we could use beatportdl with this subscription in 128 aac ...beatport seems to change something...:)
with professional it work fine

**Comment by unspok3n** [comment]
> hi ![image](https://private-user-images.githubusercontent.com/189516634/389263601-aaba33fc-6bd3-4558-b89a-379c18b53ef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NDQ2MjQsIm5iZiI6MTczMjQ0NDMyNCwicGF0aCI6Ii8xODk1MTY2MzQvMzg5MjYzNjAxLWFhYmEzM2ZjLTZiZDMtNDU1OC1iODlhLTM3OWMxOGI1M2VmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxMDMyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzA0NmRiYmVmN2RjY2VjNDUyOWVmYjNkNmQwOTRlM2MxNzZiMjVlMjE3ZGE2NzU2NTBjOTY0ZWUzNTliYjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IVjMKg-DkeR3qvSSFVK0BPt4Yu4rM6M2_hUNOxDFJlI)
> 
> with advanced subcription... by the past we could use beatportdl with this subscription in 128 aac ...beatport seems to change something...:) with professional it work fine

What quality did you use in the config to get this error?

**Comment by Darkdani31** [comment]
with the advanced subscription (the 2nd) you have not possibility to choose. I think it's automatic in 128 aac.
But with the professional subscription it works with the flac files

**Comment by djape1** [comment]
> Hi, are you sure that you have the right beatport streaming subscription?

I haven't subscription yet. I understood the point.
Thnks a lot!
