### ISSUE TITLE
fetch track: request failed with status code: 403 - Territory Restricted.

### ISSUE THREAD

**Issue by capodeicapii** [unspok3n/beatportdl#12]
Hi,

Loving the project so far, but I ran into an issue with a few tracks. When trying to fetch them, I get this error:
fetch track: request failed with status code: 403 - Territory Restricted.

Here’s an example of a track that triggers this error:
https://www.beatport.com/track/after-five/19676358

Most other tracks work fine, so I’m wondering if this is a geo-restriction issue or something else. Could it be related to licensing limitations for certain regions? Let me know if there’s a workaround or if you need any additional logs or details.

Thanks again!

**Comment by JorickDJ** [comment]
Some labels geo restrict their songs. Maybe there’s another label that also released it, but otherwise you cannot download it..

**Comment by capodeicapii** [comment]
> Some labels geo restrict their songs. Maybe there’s another label that also released it, but otherwise you cannot download it..

Oh ok I see and even with a proxy or something you think ?

**Comment by JorickDJ** [comment]
That might work, but then you have to find out what territory is allowed.

**Comment by capodeicapii** [comment]
yeah pretty sure it's bcse of that bcse i tried with multiple proxy locations and same issue.

**Comment by unspok3n** [comment]
Also worth mentioning that some tracks are bugged and may be accessible in the web app but territory restricted via public api

**Comment by cheesetosti** [comment]
Pre-orders also say they're geolocked even though they're only unavailable due to being a pre-order
