### ISSUE TITLE
OBLIGATORY TO HAVE professional subscription ?

### ISSUE THREAD

**Issue by Darkdani31** [unspok3n/beatportdl#14]
Hi
thanks for your job. Amazing project

i always have this error with my subscription advanced on beatport . The format with this subscription is max AAC 128.
![image](https://github.com/user-attachments/assets/6e0d5f36-5dc7-47c8-8ab5-f82615c6fc97)

can you confirm me there no solution for that and we are obliged to take a professional subcription with FLAC ?

Thanks

**Comment by unspok3n** [comment]
Hi, are you talking about bypassing the 128 AAC limit or just getting the downloader to work? If you want to download in 128 AAC you have to set the quality to medium in the `beatportdl-config.yml` file
```yaml
quality: medium
```

**Comment by Darkdani31** [comment]
i use the windows program and i have not the possibility to choose the quality. WHen i edit the Yml config, i have just choice of user, pass et folder of destination.==> 
![image](https://github.com/user-attachments/assets/91d5f710-2168-452e-8832-64d929763949)
so the downloder dont work with the medium subscription (which allow 128 aac and not flac )

**Comment by unspok3n** [comment]
The quality option is not in the config by default, you have to add it by yourself

**Comment by Darkdani31** [comment]
i'm a beginner ;)
i try to test that thanks

**Comment by Darkdani31** [comment]
it's done and that works fine ! thank a lot
