### ISSUE TITLE
403 from beatport

### ISSUE THREAD

**Issue by philipp1669** [unspok3n/beatportdl#17]
yesterday everything worked, now when I try downloading tracks, it throws this error: `save track: request failed with status code: 403 - You do not have permission to perform this action.`. I have already tried refreshing the token, my credentials are ok, because oauth works. I am on arm macOS

**Comment by philipp1669** [comment]
![image](https://github.com/user-attachments/assets/73fe71d8-de84-4c27-9f20-7801ec310c4b)

**Comment by unspok3n** [comment]
Just tested and everything works for me, maybe your subscription has expired?

**Comment by philipp1669** [comment]
nope, my subscription is still intact, I got the essential plan. maybe I've reached a rate limit (unlikely, I have maybe downloaded 10 songs in the last 24 hours). do you have any idea what could be the case here? I also tried it on my windows 11 vm and with a new copy of the installer, on windows it worked yesterday too (same credentials, just regenerated the token)

**Comment by philipp1669** [comment]
which subscription do you have? it has to be a huge coincidence for them to have changed it overnight. maybe its ip locked now? in safari im connected to a vpn, ill log in on another browser without one. maybe that fixes it. also updated my password, no fix.

**Comment by unspok3n** [comment]
I have professional, just created a new account with essential trial and can confirm that download endpoint is no longer working

**Comment by philipp1669** [comment]
will it work with advanced?

**Comment by unspok3n** [comment]
Tested, it works, but you have to set the quality to "medium" in the config

**Comment by unspok3n** [comment]
I'll try to add the support for essential asap

**Comment by philipp1669** [comment]
I just upgraded to advanced, it works now but LMK when it's available at essential again. Thanks

**Comment by unspok3n** [comment]
Should be working on essential now, update and try setting the quality to `medium-hls`
17ca4ce2ab68422c27b7e435ea5b432eb16dd19e 29d0657c3c9dda8dd9c3f47b6a347fba95f800fc

You should also have ffmpeg installed, since /stream endpoint returns raw AAC that needs to be wrapped in an M4A container
