### ISSUE TITLE
Formats in config not respected

### ISSUE THREAD

**Issue by cheesetosti** [unspok3n/beatportdl#19]
When downloading, my config only respects my download dir & Track File template, but not the Release Dir template:

downloads_directory: "/home/Music"
release_directory_template: "[{catalog_number}] {artists} - {name}"
track_file_template: "{number}. {artists} - {name} ({mix_name})"

**Comment by cheesetosti** [comment]
I've compiled from the last source code, changed my .yml config to this, but still doesn't download releases to a folder:
```
downloads_directory: "/nas/Music/#unsorted/"
create_release_directory: true
release_directory_template: "[{catalog_number}] {artists} - {name}"
track_file_template: "{number}. {artists} - {name} ({mix_name})"
```

**Comment by cheesetosti** [comment]
I've compiled from the last source code, changed my .yml config to this, but still doesn't download releases to a folder:
```
downloads_directory: "/home/Music"
create_release_directory: true
release_directory_template: "[{catalog_number}] {artists} - {name}"
track_file_template: "{number}. {artists} - {name} ({mix_name})"
```

**Comment by cheesetosti** [comment]
Compiling command if it makes sense:
`CGO_ENABLED=1 LINUX_AMD64_LIB_PATH="/usr/lib/x86_64-linux-gnu" CGO_LDFLAGS="-L/usr/lib/x86_64-linux-gnu" CGO_CFLAGS="-I/usr/include/taglib" make linux-amd64`

**Comment by unspok3n** [comment]
Use `sort_by_context` on the latest version, also, when compiling you can set all the flags in `LINUX_AMD64_LIB_PATH`
```
LINUX_AMD64_LIB_PATH="-L/usr/local/lib -I/usr/local/include/taglib -L/lib/x86_64-linux-gnu" make linux-amd64
```
