### ISSUE TITLE
'tag_c.h' file not found

### ISSUE THREAD

**Issue by meowingtons0808** [unspok3n/beatportdl#20]
internal/taglib/taglib.go:6:11: fatal error: 'tag_c.h' file not found
    6 |         #include <tag_c.h>
      |                  ^~~~~~~~~
1 error generated.
make: *** [darwin-amd64] Error 1

can i fix this?

**Comment by unspok3n** [comment]
You have to provide a path to the [taglib](https://github.com/taglib/taglib/blob/master/INSTALL.md) library and headers with envrionment variable when building using Makefile
https://github.com/unspok3n/beatportdl?tab=readme-ov-file#building

`MACOS_AMD64_LIB_PATH="-L/usr/local/lib -I/usr/local/include/taglib" make darwin-amd64`

**Comment by meowingtons0808** [comment]
arigatou

**Comment by meowingtons0808** [comment]
running zig failed: exit status 1

whats happening"

**Comment by unspok3n** [comment]
Any error messages? Do you have all the dependencies that are specified in the building readme section installed?
