### ISSUE TITLE
Multiple URL's trouble

### ISSUE THREAD

**Issue by SquashingBugs** [unspok3n/beatportdl#22]
Hello,

I'm trying to add multiple urls, for example:
"https://www.beatport.com/track/dirty-cash-money-talks/19727460 https://www.beatport.com/track/palm-of-my-hands/19711254" separated by spaces, but it get: "parse url: invalid url". On another downloader, this worked just fine, but would like to see it work here too.

Also:

In this 1st photo, all 5 url's download like this:
![example1](https://github.com/user-attachments/assets/cfb0ed84-9370-4629-8577-57f2ab633936)

But in the 2nd photo, only the first 4 url's download and the last one doesn't:
![example2](https://github.com/user-attachments/assets/4159a752-1d86-4e7c-b84e-f6f11e63011c)

Noticed how in the 1st, photo, all 5 lines are highlighted, while in the 2nd line, 4 lines are highlighted, while the 5 line is highlighted only up to the end of the url. Some users might miss the last url if they're not paying attention to how they're copying and pasting.

Also, I don't know how to use the /beatportdl command, since when I do it, along with anything after it, all I get is search results, and when I try to queue up .txt files, same result. I think I'm missing something here.

**Comment by zhordon** [comment]
Copy and paste all your downloads links into a .txt file. Similar to how you have it listed above.

Open Terminal or Command Prompt (whatever you’re using), go to the directory where beatportdl is located. Type the name of the beatportdl file and then point it to the path of your .txt file. 

This is the cleaner method to multiple downloads.

**Comment by cheesetosti** [comment]
Or you can escape the newline with `/n`:

`https://www.beatport.com/track/dirty-cash-money-talks/19727460 \n https://www.beatport.com/track/palm-of-my-hands/19711254`

But downloading from a .txt file would be preferable then
