### ISSUE TITLE
Feature Request: Multiple Artist Rosters for an album to be combined to: "Various Artists" or "VA", depending on what the user wants.

### ISSUE THREAD

**Issue by SquashingBugs** [unspok3n/beatportdl#24]
I think this would be pretty handy, to resolve having these albums with these large artist lists, and simplifying it with "VA" or "Various Artists".

I was thinking maybe 2 new config parameters. 1 parameter being how many artist names it would take to merge in to "VA" or "Various Artists" (e.g. 3, or 5 artist names). The other parameter being the name to rename these artists to, whether it'd be "VA", "Various Artists",  or the name equivilent in another language.

**Comment by SquashingBugs** [comment]
Here's an example of what I'm talking about:
![Screen Shot 2024-11-30 at 10 08 24 PM](https://github.com/user-attachments/assets/95a6a022-8bcc-4045-b808-c45794245caf)
As you see, some of these releases are VA compilations. By creating this solution, this prevents all of these artist names from dominiating the filename and cutting out the other important info like the Title, and the Release Date.

**Comment by unspok3n** [comment]
980a2d26340688b76f50bd17803a95e43f82bce2

**Comment by qyraai** [comment]
How can I separate my files into folders? I read the configuration file about, but not work for me. 

Here is my file

> username: [-=-=-=-=]
> password: [-=-=-=-=-]
> downloads_directory: /home/server/beatdl
> quality: lossless
> sort_by_context: true
> fix_tags: true
> release_directory_template: "[{catalogNumber}] {artists} - {name}"
> track_file_template: "{number}. {artists} - {name} ({mixName})"


But all files come orphaned at download path /home/server/beatdl No folders created. 
What I'm doing wrong?

**Comment by unspok3n** [comment]
> How can I separate my files into folders? I read the configuration file about, but not work for me.
> 
> Here is my file
> 
> > username: [-=-=-=-=]
> > password: [-=-=-=-=-]
> > downloads_directory: /home/server/beatdl
> > quality: lossless
> > sort_by_context: true
> > fix_tags: true
> > release_directory_template: "[{catalogNumber}] {artists} - {name}"
> > track_file_template: "{number}. {artists} - {name} ({mixName})"
> 
> But all files come orphaned at download path /home/server/beatdl No folders created. What I'm doing wrong?

Are you running the latest version? `sort_by_context` was introduced in v1.0.4, before that version `create_release_directory` was used. Also, template keywords use camel case (`catalog_number`)

**Comment by qyraai** [comment]
> > How can I separate my files into folders? I read the configuration file about, but not work for me.
> > Here is my file
> > > username: [-=-=-=-=]
> > > password: [-=-=-=-=-]
> > > downloads_directory: /home/server/beatdl
> > > quality: lossless
> > > sort_by_context: true
> > > fix_tags: true
> > > release_directory_template: "[{catalogNumber}] {artists} - {name}"
> > > track_file_template: "{number}. {artists} - {name} ({mixName})"
> > 
> > 
> > But all files come orphaned at download path /home/server/beatdl. No folders were created. What I'm doing wrong?
> 
> Are you running the latest version? `sort_by_context` was introduced in v1.0.4, before that version `create_release_directory` was used. Also, template keywords use snake case (`catalog_number`)

Hi, - Yes, I'm using new version 1.0.4 
Still can't get it.. :(

**Comment by unspok3n** [comment]
> > > How can I separate my files into folders? I read the configuration file about, but not work for me.
> > > Here is my file
> > > > username: [-=-=-=-=]
> > > > password: [-=-=-=-=-]
> > > > downloads_directory: /home/server/beatdl
> > > > quality: lossless
> > > > sort_by_context: true
> > > > fix_tags: true
> > > > release_directory_template: "[{catalogNumber}] {artists} - {name}"
> > > > track_file_template: "{number}. {artists} - {name} ({mixName})"
> > > 
> > > 
> > > But all files come orphaned at download path /home/server/beatdl. No folders were created. What I'm doing wrong?
> > 
> > 
> > Are you running the latest version? `sort_by_context` was introduced in v1.0.4, before that version `create_release_directory` was used. Also, template keywords use snake case (`catalog_number`)
> 
> Hi, - Yes, I'm using new version 1.0.4 Still can't get it.. :(

Do any other config options work? Is the config file in the same folder as the beatportdl executable?

**Comment by qyraai** [comment]
> > > > How can I separate my files into folders? I read the configuration file about, but not work for me.
> > > > Here is my file
> > > > > username: [-=-=-=-=]
> > > > > password: [-=-=-=-=-]
> > > > > downloads_directory: /home/server/beatdl
> > > > > quality: lossless
> > > > > sort_by_context: true
> > > > > fix_tags: true
> > > > > release_directory_template: "[{catalogNumber}] {artists} - {name}"
> > > > > track_file_template: "{number}. {artists} - {name} ({mixName})"
> > > > 
> > > > 
> > > > But all files come orphaned at download path /home/server/beatdl. No folders were created. What I'm doing wrong?
> > > 
> > > 
> > > Are you running the latest version? `sort_by_context` was introduced in v1.0.4, before that version `create_release_directory` was used. Also, template keywords use snake case (`catalog_number`)
> > 
> > 
> > Hi, - Yes, I'm using new version 1.0.4 Still can't get it.. :(
> 
> Do any other config options work? Is the config file in the same folder as the beatportdl executable?

Thank you for your reply.

Here is my configuration. 

sort_by_context: true
fix_tags: false
release_directory_template: "[{catalog_number}] {artists} - {name}"
track_file_template: "{number}. {artists} - {name} ({mix_name})"

however, the downloads files get into the folders like this:

<img width="384" alt="Screenshot 2024-12-04 at 9 34 34 PM" src="https://github.com/user-attachments/assets/705218df-9aff-4ff1-bb79-83ced8bfdb21">
<img width="449" alt="Screenshot 2024-12-04 at 9 33 44 PM" src="https://github.com/user-attachments/assets/a2542812-ac87-4789-9506-be72d8511525">

**Comment by unspok3n** [comment]
> > > > > How can I separate my files into folders? I read the configuration file about, but not work for me.
> > > > > Here is my file
> > > > > > username: [-=-=-=-=]
> > > > > > password: [-=-=-=-=-]
> > > > > > downloads_directory: /home/server/beatdl
> > > > > > quality: lossless
> > > > > > sort_by_context: true
> > > > > > fix_tags: true
> > > > > > release_directory_template: "[{catalogNumber}] {artists} - {name}"
> > > > > > track_file_template: "{number}. {artists} - {name} ({mixName})"
> > > > > 
> > > > > 
> > > > > But all files come orphaned at download path /home/server/beatdl. No folders were created. What I'm doing wrong?
> > > > 
> > > > 
> > > > Are you running the latest version? `sort_by_context` was introduced in v1.0.4, before that version `create_release_directory` was used. Also, template keywords use snake case (`catalog_number`)
> > > 
> > > 
> > > Hi, - Yes, I'm using new version 1.0.4 Still can't get it.. :(
> > 
> > 
> > Do any other config options work? Is the config file in the same folder as the beatportdl executable?
> 
> Thank you for your reply.
> 
> Here is my configuration.
> 
> sort_by_context: true fix_tags: false release_directory_template: "[{catalog_number}] {artists} - {name}" track_file_template: "{number}. {artists} - {name} ({mix_name})"
> 
> however, the downloads files get into the folders like this:
> 
> <img alt="Screenshot 2024-12-04 at 9 34 34 PM" width="384" src="https://private-user-images.githubusercontent.com/180792028/392541273-705218df-9aff-4ff1-bb79-83ced8bfdb21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDIzMDMsIm5iZiI6MTczMzM0MjAwMywicGF0aCI6Ii8xODA3OTIwMjgvMzkyNTQxMjczLTcwNTIxOGRmLTlhZmYtNGZmMS1iYjc5LTgzY2VkOGJmZGIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxOTUzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2IyOTE3Y2FhMzhkMjNiYjE4MmE0OGUyZTQ3ZmE4MDUwN2E1M2JjOWJkZGRkMDJjYzVjN2I4NWNiZDdmZWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nAanV05K5nMykqVLi7asr2zBsZ2q0lRcLfdrvN1YMKo"> <img alt="Screenshot 2024-12-04 at 9 33 44 PM" width="449" src="https://private-user-images.githubusercontent.com/180792028/392541280-a2542812-ac87-4789-9506-be72d8511525.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDIzMDMsIm5iZiI6MTczMzM0MjAwMywicGF0aCI6Ii8xODA3OTIwMjgvMzkyNTQxMjgwLWEyNTQyODEyLWFjODctNDc4OS05NTA2LWJlNzJkODUxMTUyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxOTUzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTFhYjJkOWRiZmQ4MjIzNDlmZjE1YmJkNTI5ZTVjMTE4ZTBlNzQwNzE5YjcyNzhlMTQ4ODFkYjQwN2E4ODVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._XvkoRU8W0c7HglGfDf7MSZG2B_RhrCUlWL56sxvccA">

It looks like it uses your previous config options, do you restart beatportdl after changing the config?

**Comment by qyraai** [comment]
> > > > > > How can I separate my files into folders? I read the configuration file about, but not work for me.
> > > > > > Here is my file
> > > > > > > username: [-=-=-=-=]
> > > > > > > password: [-=-=-=-=-]
> > > > > > > downloads_directory: /home/server/beatdl
> > > > > > > quality: lossless
> > > > > > > sort_by_context: true
> > > > > > > fix_tags: true
> > > > > > > release_directory_template: "[{catalogNumber}] {artists} - {name}"
> > > > > > > track_file_template: "{number}. {artists} - {name} ({mixName})"
> > > > > > 
> > > > > > 
> > > > > > But all files come orphaned at download path /home/server/beatdl. No folders were created. What I'm doing wrong?
> > > > > 
> > > > > 
> > > > > Are you running the latest version? `sort_by_context` was introduced in v1.0.4, before that version `create_release_directory` was used. Also, template keywords use snake case (`catalog_number`)
> > > > 
> > > > 
> > > > Hi, - Yes, I'm using new version 1.0.4 Still can't get it.. :(
> > > 
> > > 
> > > Do any other config options work? Is the config file in the same folder as the beatportdl executable?
> > 
> > 
> > Thank you for your reply.
> > Here is my configuration.
> > sort_by_context: true fix_tags: false release_directory_template: "[{catalog_number}] {artists} - {name}" track_file_template: "{number}. {artists} - {name} ({mix_name})"
> > however, the downloads files get into the folders like this:
> > <img alt="Screenshot 2024-12-04 at 9 34 34 PM" width="384" src="https://private-user-images.githubusercontent.com/180792028/392541273-705218df-9aff-4ff1-bb79-83ced8bfdb21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDIzMDMsIm5iZiI6MTczMzM0MjAwMywicGF0aCI6Ii8xODA3OTIwMjgvMzkyNTQxMjczLTcwNTIxOGRmLTlhZmYtNGZmMS1iYjc5LTgzY2VkOGJmZGIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxOTUzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2IyOTE3Y2FhMzhkMjNiYjE4MmE0OGUyZTQ3ZmE4MDUwN2E1M2JjOWJkZGRkMDJjYzVjN2I4NWNiZDdmZWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nAanV05K5nMykqVLi7asr2zBsZ2q0lRcLfdrvN1YMKo"> <img alt="Screenshot 2024-12-04 at 9 33 44 PM" width="449" src="https://private-user-images.githubusercontent.com/180792028/392541280-a2542812-ac87-4789-9506-be72d8511525.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDIzMDMsIm5iZiI6MTczMzM0MjAwMywicGF0aCI6Ii8xODA3OTIwMjgvMzkyNTQxMjgwLWEyNTQyODEyLWFjODctNDc4OS05NTA2LWJlNzJkODUxMTUyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxOTUzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTFhYjJkOWRiZmQ4MjIzNDlmZjE1YmJkNTI5ZTVjMTE4ZTBlNzQwNzE5YjcyNzhlMTQ4ODFkYjQwN2E4ODVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._XvkoRU8W0c7HglGfDf7MSZG2B_RhrCUlWL56sxvccA">
> 
> It looks like it uses your previous config options, do you restart beatportdl after changing the config?

After the restart was fixed and downloads saved correctly. 

Best Regards
