### ISSUE TITLE
Config option to create a .txt file listing all Territory Restricted and Non-Streamable releases, as well as any track that fails to download for any reason.

### ISSUE THREAD

**Issue by SquashingBugs** [unspok3n/beatportdl#25]
To help make it easier to track which tracks to make note of and possibly to get with different streaming service.

**Comment by zhordon** [comment]
I like this as a feature request myself, as I've been manually tracking those type of tracks/releases myself.

I don't think it's for the Dev to work that out for us, plus Beatport's API is a bit bugged for those types of error. It can show a track being streamable on the website while logged in, but it will throw an error of Territory Restricted when you go to download it.

That being said, If it's not much work for the dev to implement it as a "Error.log" that caches those errored release/tracks with the link. If it's too much work for the dev, I understand why it can't be.

**Comment by unspok3n** [comment]
41c6463e23ebf76f9d1baf3bdde1670492967f34

**Comment by zhordon** [comment]
I can confirm the feature works on the lastest commit.

write_error_log: true

Issue should be officially closed once a new build is released officially.
