### ISSUE TITLE
A config option to add labels as a parent directory for downloading releases.

### ISSUE THREAD

**Issue by SquashingBugs** [unspok3n/beatportdl#26]
By doing this, it means I can download multiple release links at once from various different labels, and have them all be sorted into labels. This is useful for queuing up thousands of links at once and have your computer do a download all-nighter while you sleep, then you wake up and all of your releases are neatly sorted into label folders.

**Comment by unspok3n** [comment]
ab9ef774504ee60055b1580fe7edc628327f05fd

**Comment by evgeniy702** [comment]
> [ab9ef77](https://github.com/unspok3n/beatportdl/commit/ab9ef774504ee60055b1580fe7edc628327f05fd)

When i start download from label link, beatportdl try start rename covers and was next messages: The system cannot find the file specified.

**Comment by unspok3n** [comment]
> > [ab9ef77](https://github.com/unspok3n/beatportdl/commit/ab9ef774504ee60055b1580fe7edc628327f05fd)
> > When i start download from label link, beatportdl try start rename covers and was next messages: The system cannot find the file specified.
> > ![Снимок экрана 2024-12-05 162901](https://private-user-images.githubusercontent.com/35782410/392791973-560d6f64-88fc-42a7-b370-abbfb722da7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MjM2NTksIm5iZiI6MTczMzQyMzM1OSwicGF0aCI6Ii8zNTc4MjQxMC8zOTI3OTE5NzMtNTYwZDZmNjQtODhmYy00MmE3LWIzNzAtYWJiZmI3MjJkYTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE4MjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNGRkODljYzI0NDk0MThhYWQzYWY4OWRhNDZjYzJlNmM1YWE3YmMxYzFmYTc2MjNkMWQ2YzhhOGZiODk5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CPufQSISa_VqCblRKnS6p1Um8m9m8KEc5tyKefde6Us)
> > ![Снимок экрана 2024-12-05 163651](https://private-user-images.githubusercontent.com/35782410/392795908-08c7bc94-d831-4a5f-a9c2-3f5298d584ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MjM2NTksIm5iZiI6MTczMzQyMzM1OSwicGF0aCI6Ii8zNTc4MjQxMC8zOTI3OTU5MDgtMDhjN2JjOTQtZDgzMS00YTVmLWE5YzItM2Y1Mjk4ZDU4NGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE4MjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNWUwNjgwOGE1NDYxZjcxMDIxOTAyNDRlNDUyNjUwOTcyNGRkNDYyMmJhNDRlMTdmZmVhOWJmYmJkZjkzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ylqGZy5ST8FRAH6ty_4GAexuZMhtslr69zXO0BMp9NY)

Should be fixed 32267692c015116f5858f3c1d3db309e9d6d60ee
