### ISSUE TITLE
Stream error when downloading many releases

### ISSUE THREAD

**Issue by Phytride** [unspok3n/beatportdl#29]
When downloading from one or couple more links with Beatportdl, it successfully downloads all tracks with no problem. But when I feed it 25 or more links at once, I experience high chances of failure with the majority of the tracks, resulting in incomplete files. I get stream error and INTERNAL_ERROR received from peer. It could be related to the fact that the program downloads every track simultaneously, instead of grabbing each track one by one.

**Comment by SquashingBugs** [comment]
I think a solution to this would be to cap concurrent downloads. 5 could be the default number, but can be increased/decreased with a config setting.

**Comment by evil1kenny** [comment]
I believe we should be a bit more modest, don't you think? You've been given the opportunity to download music for free, and now you're getting greedy, downloading it in bulk. Someone even suggested adding the option to download by labels. Greed is a bad thing

**Comment by cheesetosti** [comment]
Sir this is a github issues page, not a church

**Comment by cheesetosti** [comment]
> I believe we should be a bit more modest, don't you think? You've been given the opportunity to download music for free, and now you're getting greedy, downloading it in bulk. Someone even suggested adding the option to download by labels. Greed is a bad thing

Sir this is a github issues page, not a church

**Comment by unspok3n** [comment]
32c8d9c41e0e01c0acc9e61d2b4d460feca39d7d
