### ISSUE TITLE
Request: Multiple urls from text-file

### ISSUE THREAD

**Issue by bascurtiz** [unspok3n/beatportdl#3]
Handy tool! (next to OrhpeusDL)

Could u make it so, that it accepts a text-file with urls per line to download multiple ones after another?

I tried to enter multiple urls as input, with a space in between the urls, but that won't budge.

**Comment by unspok3n** [comment]
Done 3a46883c8dd356f0fbe96850d3b5ccd1618da5f0

**Comment by bascurtiz** [comment]
\o/
Thanks!
Will test-drive it asap

**Comment by bascurtiz** [comment]
Works!
![image](https://github.com/user-attachments/assets/f8837ace-726c-4603-a2e6-0587a2be55f2)
