### ISSUE TITLE
Save the AlbumArtist tag

### ISSUE THREAD

**Issue by qyraai** [unspok3n/beatportdl#33]
Hello, 

Is it possible to save the ID3Tag "Albumartist" from Beatport? It will be useful to separate different albums from download folder accurately.

Thank you

**Comment by unspok3n** [comment]
3435c829c54c3fc4c5f99c87c07b46cf50645498

**Comment by qyraai** [comment]
> [3435c82](https://github.com/unspok3n/beatportdl/commit/3435c829c54c3fc4c5f99c87c07b46cf50645498)

Thank you for your effort. I love your software
