### ISSUE TITLE
Weird spaces/tabs in folder/file names

### ISSUE THREAD

**Issue by cheesetosti** [unspok3n/beatportdl#34]
Downloading this release
https://www.beatport.com/release/mayday-dream-unite/172242

results in
`[DWX011	] Deepack, Coone - Mayday Dream   Unite 			 (2009)`
`01. Deepack, Coone - Mayday Dream (Bonzai Tribute)			 (Original Mix).flac`

**Comment by unspok3n** [comment]
Track name, release name and catalog number contains tabs, looks like beatport wasn't sanitizing inputs back in 2009.
```json
{
    "catalog_number": "DWX011\t",
    "name": "Mayday Dream (Bonzai Tribute)\t\t\t",
    "release": {
        "name": "Mayday Dream /  Unite \t\t\t"
    }
}
```

Added custom unmarshaling method de84bace6693a434f006fdb6c259596d3fe4a8ce

**Comment by cheesetosti** [comment]
Thank you!
