### ISSUE TITLE
Tag "CATALOGNUMBER" didn't add to tags in .flac

### ISSUE THREAD

**Issue by evgeniy702** [unspok3n/beatportdl#36]
Tag "CATALOGNUMBER" didn't add to tags in .flac . can't make this working((
![Снимок экрана 2024-12-06 064145](https://github.com/user-attachments/assets/113f2809-d915-4523-b039-015a2334a45c)

**Comment by cheesetosti** [comment]
It does work for me when I build the binary myself from the latest source code

**Comment by evgeniy702** [comment]
> It does work for me when I build the binary myself from the latest source code

for me it doesnt work. i build from latest source code too. but it doestnt work(

**Comment by unspok3n** [comment]
AIMP takes catalog number from `LABELNO` tag but BeatportDL writes it to `CATALOGNUMBER`

**Comment by evgeniy702** [comment]
> LABELNO

Now it works fine! Thanks !
![Снимок экрана 2024-12-07 225237](https://github.com/user-attachments/assets/51e302d3-ffd8-473f-a9ed-decfb61e28a7)
