### ISSUE TITLE
Request: download track by track

### ISSUE THREAD

**Issue by meowingtons0808** [unspok3n/beatportdl#37]
hi bro

I want to request for download one by one for safety first

because download one time in a row isn't safe.

;)

**Comment by cheesetosti** [comment]
So he is asking for a config setting for max concurrent downloads

**Comment by unspok3n** [comment]
You can set `max_download_workers` to 1, but honestly i see no point in limiting it like that, what kind of safety are you trying to achieve here?

**Comment by meowingtons0808** [comment]
> You can set `max_download_workers` to 1, but honestly i see no point in limiting it like that, what kind of safety are you trying to achieve here?

thanks!!

**Comment by bascurtiz** [comment]
I'm downloading 2k+ with a txt-file using Windows:
`beatportdl-windows-amd64 urls.txt`

It populates a list.
When d/ling to HDD it's not fast enough to keep up, reviewing it's constant at 100% writing.
When d/ling to SSD it's fast enough to keep up, but then I get several warnings like below:
```
save track: download file: Get "https://assets.beatportprod.com/flac-44100hz/5/a/c/5acd7761-bdd6-4b8f-9b33-c951c988d80e.flac?response-content-disposition=attachment&Expires=1734175145&KeyName=beatport-signing-key&Signature=DKr3CeNSoReDba9Q=":
dial tcp 34.117.52.79:443:
bind: An operation on a socket cannot be performed because the system has insufficient buffer space or because a queue is full.
```
It ends up with 1k downloaded and 400+ of them are 0 bytes.

I've tried setting the amount of workers to 1 in beatportdl-config.yaml, like this:
`max_download_workers: 1` right below `downloads_directory:` and `username:` and `password:`

yet, it doesn't solve the above warning.
could it be the fact release v1.0.4 didn't support `max_download_workers` yet?

If that's the case, could u build a new release?
