### ISSUE TITLE
Wich release/track got errors?

### ISSUE THREAD

**Issue by evgeniy702** [unspok3n/beatportdl#42]
when i download from label/release link, i don't understand, wich file or folder not downloaded or have any errors. info from file "error" (in downloader too) not usefull for release/label links, 
![Снимок экрана 2024-12-16 003156](https://github.com/user-attachments/assets/2f9ae2dd-9cc8-43b7-9ad3-2a1d705112d8)
![Снимок экрана 2024-12-16 004752-1](https://github.com/user-attachments/assets/9fb4514e-ea3f-43bd-ae4e-08698dd8f4f0)

**Comment by SquashingBugs** [comment]
Can confirm. I get the following error for a territory restricted track, yet I have no idea which track is territory restricted.
![error](https://github.com/user-attachments/assets/beb90a5d-1fce-463e-bad5-36920849abf9)

**Comment by SquashingBugs** [comment]
I also find it strange with the completed releases being spammed as complete multiple times. I don't know if the same track is being written multiple times, or just a visual bug, but the tracks appear to download normal when browsing them.

**Comment by SquashingBugs** [comment]
https://we.tl/t-fPawVXXUCn

Does weird stuff after downloading a bunch of label links. Using macOS 12.7.6

**Comment by unspok3n** [comment]
1313a4cb968b708b71d9c11a5d55f0e95bc869e5

example label download:
```
[https://www.beatport.com/release/ping-pong-ep/4834516] handle release tracks: fetch page: request failed with status code: 403 - Territory Restricted.
[https://www.beatport.com/release/dogma-infinite-falling-ground/3839126] download release cover: bad status: 404 Not Found
[https://www.beatport.com/release/skin/3709433] download release cover: bad status: 404 Not Found
[https://www.beatport.com/release/prowlerfragment/3594226] download release cover: bad status: 404 Not Found
[https://www.beatport.com/release/blonde/3173862] download release cover: bad status: 404 Not Found
[https://www.beatport.com/release/cake-shades-remix/2969566] download release cover: bad status: 404 Not Found
[https://www.beatport.com/release/space-war/2762528] download release cover: bad status: 404 Not Found
[https://www.beatport.com/release/gunk/2554221] download release cover: bad status: 404 Not Found
[https://www.beatport.com/release/cracks/2554219] download release cover: bad status: 404 Not Found
```

**Comment by unspok3n** [comment]
> I also find it strange with the completed releases being spammed as complete multiple times. I don't know if the same track is being written multiple times, or just a visual bug, but the tracks appear to download normal when browsing them.

It's only a visual bug, this is just how the underlying progress bar library works, the duplicates appear only when scrolling.

**Comment by unspok3n** [comment]
> https://we.tl/t-fPawVXXUCn
> 
> Does weird stuff after downloading a bunch of label links. Using macOS 12.7.6

That's not how you should submit multiple links, either provide a text file or use positional arguments, main prompt isn't intended to support multiple links.
