### ISSUE TITLE
[QUESTION] Help Running

### ISSUE THREAD

**Issue by s31teg** [unspok3n/beatportdl#47]
### Question

Hello

Apologies for this probs stupid question for you.

I've downloaded beatportdl-darwin-arm64 for my m mac. 
Put it in a folder
I tried to run with no luck.

What am I doing wrong?

TIA

![Capture-1812-2131-000333@2x](https://github.com/user-attachments/assets/7fdedcc9-65a1-4fdc-90c5-e6bd08c47570)

**Comment by unspok3n** [comment]
Hi, no worries, you have to add execute permission to the binary:
```shell
chmod +x beatportdl-darwin-arm64
```

**Comment by s31teg** [comment]
Amazing, that worked :)
