### ISSUE TITLE
[BUG] No album art on flac

### ISSUE THREAD

**Issue by s31teg** [unspok3n/beatportdl#48]
### Description

I see when using flac settings the album artwork is not there. Not sure if this is a limitation or bug

### Steps To Reproduce

Using 1.0.5 pre compiled

Example url: https://www.beatport.com/track/home-in-that-bass/19449350

### OS

M4 Mac 15.1.1

### Version

1.0.5

**Comment by zhordon** [comment]
macOS doesn’t support .FLAC natively in the sense that it will not show the Album Cover on the file, it will in a Player and Tag Editor.

You would need to convert your FLAC to ALAC which would make it appear correctly in a macOS environment.

I also use a M1 Max system as well.

**Comment by s31teg** [comment]
Tbh high quality is all I need but thanks for the understanding about flac and mac.
________________________________
