### ISSUE TITLE
[REQUEST] Skip already downloaded tracks

### ISSUE THREAD

**Issue by cheesetosti** [unspok3n/beatportdl#55]
### Description

Would be great to skip already downloaded tracks, e.g. by comparing filenames or by reading a certain vorbis tag value (release ID?), maybe add an option to define the comparing parameter in config.yml? Something like 
`compare_existing_tracks_by: "{filename} or RELEASE_ID"`
or
`compare_existing_tracks_by_filename: true`

**Comment by SquashingBugs** [comment]
And there should also be an option to overwrite tags only, but not re-download the actual file.

**Comment by unspok3n** [comment]
Added `track_exists` config option. a17d6483bcb17c64188dbc9f77e27522f7f9b291

* `error` - Log error and skip
* `skip` - Skip silently
* `overwrite` - Re-download
* `update` - Update tags (this also removes all existing tags that taglib finds)

Tracks are compared by filename.
