### ISSUE TITLE
[REQUEST] Adding SubGenres

### ISSUE THREAD

**Issue by SquashingBugs** [unspok3n/beatportdl#56]
### Description

Hello, and I would like to see this new config option for those who have "fix_tags" set to true. This new config option would be called "use_subgenre".
- "False" would be the default option
- "True" would replace "Genre" with "Subgenre" for the "Genre" tag field, but only if the track has a Sub-Genre; otherwise, it defaults to "Genre"
- "Both" would use both the "Genre" and "Subgenre" for the "Genre" tag field. Both the Genre and Subgenre would be put in the same tag field, seperated by the "|" symbol, exactly the same way that beatport seperates Genre from Subgenre. Example: https://www.beatport.com/track/el-rey/19758251 this track has the genre field "Tech House | Latin Tech". This would be 1 single field so that both names are present, which makes it friendly for iTunes/Apple Music, or other programs that only recognize 1 genre field. Again, only applicable if that track has a Subgenre, otherwise it will only display Genre.

**Comment by unspok3n** [comment]
I think tag mapping keys would be a better fit.

b150f92ddb7b174eed2207310a6efddc8eefb063 commit adds keys:
* `track_subgenre` (subgenre only, ignored if unspecified)
* `track_genre_with_subgenre` (genre with subgenre separated by ` | `, genre only if subgenre is unspecified)
* `track_subgenre_or_genre` (subgenre if available, otherwise genre)

**Comment by SquashingBugs** [comment]
> I think tag mapping keys would be a better fit.
> 
> [b150f92](https://github.com/unspok3n/beatportdl/commit/b150f92ddb7b174eed2207310a6efddc8eefb063) commit adds keys:
> 
>     * `track_subgenre` (subgenre only, ignored if unspecified)
> 
>     * `track_genre_with_subgenre` (genre with subgenre separated by `|`, genre only if subgenre is unspecified)
> 
>     * `track_subgenre_or_genre` (subgenre if available, otherwise genre)

Yeah I wrote this before I saw the tag mapping keys. Keep up the good work!
