### ISSUE TITLE
[REQUEST] To Address new additions to tagging.

### ISSUE THREAD

**Issue by SquashingBugs** [unspok3n/beatportdl#57]
### Description

Hello, and I have seen people requesting new tags, such as "TOTALTRACKS", "ALBUMARTIST", "CATALOGNUMBER", etc. however, some of us may not want these tags when we have "fixed_tags" set to true. I for instance do not want "CATALOGNUMBER" in the tags of tracks, and instead of "TOTALTRACKS" I prefer either "TRACKTOTAL", or "1/4, 2/4, etc" in "TRACK" field as I am an Apple Music user on macOS.

I think that some kind of solution should be made to address this so that everyone can be happy with their own preferences, instead of not being able to edit the tags choices they want. Having some kind of customization I think will make a lot more users happier, so that new tagging additions in the future can be decided on by the user.

**Comment by unspok3n** [comment]
Hi, sounds like this could have been already solved with the tag mappings that i added last week.

```yaml
tag_mappings:
  flac:
    key: "YOUR_TAG_NAME_HERE"
  m4a:
    key: "YOUR_TAG_NAME_HERE"
```

When you add the entry for the format in the config, only the tags that you specify are written.
Available keys: `track_id`, `track_url`, `track_name`, `track_artists`, `track_number`, `track_genre`, `track_key`, `track_bpm`, `track_isrc`, `release_id`, `release_url`, `release_name`, `release_artists`, `release_date`, `release_year`, `release_track_count`, `release_catalog_number`, `release_upc`, `release_label`, `release_label_url`

Just added the `track_number_with_total` key for the `number/total` format

**Comment by SquashingBugs** [comment]
Yeah that's why I closed this issues because I just discovered that.
